### ISSUE TITLE
How to handle double mappings from Cim Switch Code to IEC Equipment Type

### ISSUE THREAD

**Issue by dlabordus** [com-pas/compas-cim-mapping#56]
As an engineer
I want to map Cim Switch Codes to IEC Equipment Type
So I can generate 61850 single line diagrams without manual editing

Background:
Mapping is be based on IEC/TS 62361-102, chapter 5.6.2, but some CIM Codes can be mapped on multiple IEC Codes.
For instance
    CAB("ACLineSegment", "DCLineSegment"),
    GIL("ACLineSegment", "DCLineSegment"),
    IFL("ACLineSegment", "DCLineSegment", "EquivalentBranch"),
    LIN("ACLineSegment", "DCLineSegment"),
There must be decided how to handle this.

**Comment by Sander3003** [comment]
ACLineSegment is mostly used, however this needs more investigation.

**Comment by Sander3003** [comment]
Whether a AClinesegement is Gas insulated line (GIL), Power Cable (CAB), poweroverheadline (LIN) depends on the (CIM) Asset related to PSR (AClinesegement). This information is not available in the CGMES profile and the LN IFL is deprecated (Infeedline).

For now, the AClinesegement can be converted to CAB since this is mostly used in Dutch DSO grids.  This assumption needs to be clear in the documentation. 

Potential solutions for later:
Make an CIM extension to select the type of AClinesegment
Select the type of extension during the conversion.

In case of a DC line segment, the SCL voltage level:nomFreq must be set to 0.

**Comment by Sander3003** [comment]
@dlabordus does this address your decision request?
